import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Footer from "@/components/footer";
// import ReactQueryProvider from "@/components/ReactQueryProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body
          className={`${poppins} antialiased px-[30px] py-6 pb-28 overflow-x-hidden`}
        >
          {/* <ReactQueryProvider> */}
          <StoreProvider>{children}</StoreProvider>
          {/* </ReactQueryProvider> */}
          <Footer />
        </body>
      </html>
    </>
  );
}
